### ISSUE TITLE
Exprecss with plain JS

### ISSUE THREAD

**Issue by nileshsavani09** [colealanroberts/Exprecss#13]
Hi there,
I m not an AngularJS guy, i use twitter bootstrap for most of projects. I like the design and functionalities of this framework. I wanna use it in one of my project. Is there any scope to use it ? Can i use it with backbone ? Thanks. Hope someone will guide me.

**Comment by colealanroberts** [comment]
Hi @nileshsavani09,

You can use Exprecss and it's compiled stylesheet without any limitation. Unfortunately, we have no plans for a pure JS version. However, pull requests are welcome :).

Thanks!
